---
- hosts: all

  remote_user: vagrant
  sudo: yes

  vars:
   - bro_version: 2.4.1
   - fixbuf_version: 1.7.1
   - yaf_version: 2.8.0
   - snort_version: 2.9.8.0-1
   - daq_version: 2.0.6-1
   - iface: eth0
   - yaf_topic: ipfix
   - kafka_broker: localhost:9092
   - zookeeper_host: localhost:2181
   - hdp_repo_def: http://public-repo-1.hortonworks.com/HDP/centos6/2.x/updates/2.3.2.0/hdp.repo
   - pycapa_repo: https://github.com/OpenSOC/pycapa.git
   - pycapa_home: /opt/pycapa
   - pycapa_topic: pcap

  tasks:
   - include: tasks/kafka.yml
   - include: tasks/flume.yml
   - include: tasks/pycapa.yml
   - include: tasks/kafkacat.yml
   - include: tasks/yaf.yml
   - include: tasks/bro.yml
   - include: tasks/snort.yml
