---
- name: Retrieve HDP repository definition
  get_url:
    url: "{{ hdp_repo_def }}"
    dest: /etc/yum.repos.d/hdp.repo
    mode: 0644

- name: Install flume
  yum: name={{item}} state=latest update_cache=yes
  with_items:
    - java-1.8.0-openjdk
    - flume
    - flume-agent

- name: Create flume-env.sh
  shell: cp /etc/flume/conf/flume-env.sh.template /etc/flume/conf/flume-env.sh

- name: Configure flume-env.sh
  lineinfile: >
    dest=/etc/flume/conf/flume-env.sh
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    state=present
  with_items:
    - { regexp: '^.*export JAVA_HOME=.*$', line: 'export JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk.x86_64/' }

- name: Create flume service
  shell: "{{item}}"
  with_items:
    - cp /usr/hdp/current/flume-server/etc/rc.d/init.d/flume-agent /etc/init.d/

- name: Remove default flume configuration
  shell: rm -f /etc/flume/conf/flume.conf

- name: Install flume configurations
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: src/flume-ipfix.conf, dest: /etc/flume/conf/flume-ipfix.conf }
    - { src: src/flume-snort.conf, dest: /etc/flume/conf/flume-snort.conf }
    - { src: src/flume-bro.conf.template, dest: /etc/flume/conf/flume-bro-conn.conf }
    - { src: src/flume-bro.conf.template, dest: /etc/flume/conf/flume-bro-dns.conf }
    - { src: src/flume-bro.conf.template, dest: /etc/flume/conf/flume-bro-software.conf }

- name: Set kafka broker in flume
  lineinfile: >
    dest="{{ item.dest }}"
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    state=present
  with_items:
    - { dest: /etc/flume/conf/flume-ipfix.conf,
        regexp: '^ipfix\.sinks\.kafka-sink\.brokerList.*$',
        line: 'ipfix.sinks.kafka-sink.brokerList = {{ kafka_broker }}' }
    - { dest: /etc/flume/conf/flume-snort.conf,
        regexp: '^snort\.sinks\.kafka-sink\.brokerList.*$',
        line: 'snort.sinks.kafka-sink.brokerList = {{ kafka_broker }}' }
    - { dest: /etc/flume/conf/flume-bro-conn.conf,
        regexp: '^bro-conn\.sinks\.kafka-sink\.brokerList.*$',
        line: 'bro-conn.sinks.kafka-sink.brokerList = {{ kafka_broker }}' }
    - { dest: /etc/flume/conf/flume-bro-dns.conf,
        regexp: '^bro-dns\.sinks\.kafka-sink\.brokerList.*$',
        line: 'bro-dns.sinks.kafka-sink.brokerList = {{ kafka_broker }}' }
    - { dest: /etc/flume/conf/flume-bro-software.conf,
        regexp: '^bro-software\.sinks\.kafka-sink\.brokerList.*$',
        line: 'bro-software.sinks.kafka-sink.brokerList = {{ kafka_broker }}' }

- name: Set kafka topics in flume
  lineinfile: >
    dest="{{ item.dest }}"
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    state=present
  with_items:
    - { dest: /etc/flume/conf/flume-ipfix.conf,
        regexp: '^ipfix\.sinks\.kafka-sink\.topic.*$',
        line: 'ipfix.sinks.kafka-sink.topic = {{ yaf_topic }}'}
    - { dest: /etc/flume/conf/flume-snort.conf,
        regexp: '^snort\.sinks\.kafka-sink\.topic.*$',
        line: 'snort.sinks.kafka-sink.topic = {{ snort_topic }}'}
    - { dest: /etc/flume/conf/flume-bro-conn.conf,
        regexp: '^bro-conn\.sinks\.kafka-sink\.topic.*$',
        line: 'bro-conn.sinks.kafka-sink.topic = {{ bro_conn_topic }}' }
    - { dest: /etc/flume/conf/flume-bro-dns.conf,
        regexp: '^bro-dns\.sinks\.kafka-sink\.topic.*$',
        line: 'bro-dns.sinks.kafka-sink.topic = {{ bro_dns_topic }}' }
    - { dest: /etc/flume/conf/flume-bro-software.conf,
        regexp: '^bro-software\.sinks\.kafka-sink\.topic.*$',
        line: 'bro-software.sinks.kafka-sink.topic = {{ bro_software_topic }}' }
