---
- name: Retrieve HDP repository definition
  get_url:
    url: "{{ hdp_repo_def }}"
    dest: /etc/yum.repos.d/hdp.repo
    mode: 0644

- name: Install kafka
  yum: name={{item}} state=latest update_cache=no
  with_items:
    - java-1.8.0-openjdk
    - kafka
    - zookeeper-server

- name: Start zookeeper
  shell: /usr/hdp/current/zookeeper-server/bin/zookeeper-server start

- name: Start kafka
  shell: /usr/hdp/current/kafka-broker/bin/kafka start
