---
- name: Install development tools
  yum: name="@Development tools" state=present

- name: Clone kafkacat repo
  git: repo=https://github.com/edenhill/kafkacat.git dest=/tmp/kafkacat

- name: Compile and install kafkacat
  shell: "{{item}}"
  args:
    chdir: /tmp/kafkacat
    creates: /usr/local/bin/kafkacat
  with_items:
    - ./bootstrap.sh
    - make install
