---
- name: Install development tools
  yum: name="@Development tools" state=present

- name: Install prerequisites
  yum: name={{item}} state=latest update_cache=yes
  with_items:
    - libpcap
    - libpcap-devel
    - pcre
    - pcre-devel
    - glib2-devel
    - zlib
    - zlib-devel

- name: Download fixbuf
  get_url:
    url: "http://tools.netsa.cert.org/releases/libfixbuf-{{fixbuf_version}}.tar.gz"
    dest: /tmp

- name: Extract fixbuf tarball
  unarchive:
    src: "/tmp/libfixbuf-{{fixbuf_version}}.tar.gz"
    dest: /tmp
    copy: no
    creates: "/tmp/libfixbuf-{{fixbuf_version}}"

- name: Compile and Install fixbuf
  shell: "{{item}}"
  args:
    chdir: "/tmp/libfixbuf-{{fixbuf_version}}"
  with_items:
    - ./configure
    - make
    - make install

- name: Download yaf
  get_url:
    url: "http://tools.netsa.cert.org/releases/yaf-{{yaf_version}}.tar.gz"
    dest: /tmp

- name: Extract yaf tarball
  unarchive:
    src: "/tmp/yaf-{{yaf_version}}.tar.gz"
    dest: /tmp
    copy: no
    creates: /usr/local/bin/yaf

- name: Compile and install yaf
  shell: "{{item}}"
  args:
    chdir: "/tmp/yaf-{{yaf_version}}"
    creates: /usr/local/bin/yaf
  with_items:
    - ./configure --enable-applabel --enable-plugins
    - make
    - make install

- name: Create yaf service
  shell: "{{item}}"
  args:
    creates: /usr/local/etc/yaf.conf
  with_items:
    - cp /tmp/yaf-{{yaf_version}}/etc/init.d/yaf /etc/init.d/yaf
    - chmod +x /etc/init.d/yaf
    - cp /tmp/yaf-{{yaf_version}}/etc/yaf.conf /usr/local/etc/yaf.conf

- name: Configure yaf
  lineinfile: >
    dest=/usr/local/etc/yaf.conf
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    state=present
  with_items:
    - { regexp: '^ENABLED=.*$', line: 'ENABLED=1' }
    - { regexp: '^YAF_EXTRAFLAGS=.*$', line: 'YAF_EXTRAFLAGS='}
    - { regexp: '^YAF_CAP_IF=.*$', line: 'YAF_CAP_IF={{iface}}'}

- name: Install flume configuration for ipfix
  copy: src=src/flume-ipfix.conf dest=/etc/flume/conf/flume-ipfix.conf

- name: Configure ipfix destination in flume configuration
  lineinfile: >
    dest=/etc/flume/conf/flume-ipfix.conf
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    state=present
  with_items:
    - { regexp: '^agent.sinks\.kafka-sink\.brokerList.*$', line: 'agent.sinks.kafka-sink.brokerList = {{ kafka_broker }}' }
    - { regexp: '^agent.sinks\.kafka-sink\.topic.*$', line: 'agent.sinks.kafka-sink.topic = {{ yaf_topic }}'}

- name: Start flume service to consume ipfix
  service: name=flume-agent args=ipfix state=started

- name: Start yaf service to produce ipfix
  service: name=yaf state=started
